#!/bin/sh
# Usage:
# runtest [applet1] [applet2...]

. ./testing.sh

total_failed=0

# Run one old-style test.
# Tests are stored in applet/testcase shell scripts.
# They are run using "sh -x -e applet/testcase".
# Option -e will make testcase stop on the first failed command.
run_applet_testcase()
{
	applet="$1"
	testcase="$2"

	status=0
	uc_applet=$(echo "$applet" | tr a-z A-Z)
	testname="$testcase"

	testname="${testname##*/}" # take basename
	# Removed .config checks for korego

	rm -rf ".tmpdir.$applet"
	mkdir -p ".tmpdir.$applet"
	cd ".tmpdir.$applet" || return 1

	# For tar/gzip/gunzip old-style tests, create a local 'busybox' -> korego
	# symlink so 'busybox tar' etc. routes to korego instead of system busybox.
	# Also prepend LINKSDIR for tar so archive creation uses korego tar too.
	case "$applet" in
		tar)
			ln -s "$bindir/korego" busybox 2>/dev/null
			;;
		gzip|gunzip)
			ln -s "$bindir/korego" busybox 2>/dev/null
			;;
	esac

#	echo "Running testcase $testcase"
	case "$applet" in
		tar)
			PATH=".:$LINKSDIR:$PATH" d="$tsdir" \
				sh -x -e "$testcase" >"$testname.stdout.txt" 2>&1 || status=$?
			;;
		gzip|gunzip)
			PATH=".:$PATH" d="$tsdir" \
				sh -x -e "$testcase" >"$testname.stdout.txt" 2>&1 || status=$?
			;;
		*)
			d="$tsdir" \
				sh -x -e "$testcase" >"$testname.stdout.txt" 2>&1 || status=$?
			;;
	esac
	if [ $status -ne 0 ]; then
		echo "FAIL: $testname"
		if [ x"$VERBOSE" != x ]; then
			cat "$testname.stdout.txt"
		fi
	else
		echo "PASS: $testname"
	fi

	cd ..
	rm -rf ".tmpdir.$applet"

	return $status
}

# Run all old-style tests for given applet
run_oldstyle_applet_tests()
{
	local applet="$1"
	local status=0

	for testcase in "$tsdir/$applet"/*; do
		# switch on basename of $testcase
		case "${testcase##*/}" in
			.*)     continue ;;    # .svn, .git etc
			*~)     continue ;;    # backup files
			"CVS")  continue ;;
			\#*)    continue ;;    # CVS merge residues
			*.mine) continue ;;    # svn-produced junk
			*.r[0-9]*) continue ;; # svn-produced junk
		esac
		run_applet_testcase "$applet" "$testcase" || {
			status=1
			total_failed=$((total_failed + 1))
		}
	done
	return $status
}



lcwd=$(pwd)
[ x"$tsdir" != x"" ] || tsdir="$lcwd"
[ x"$bindir" != x"" ] || bindir="${lcwd%/*/*}" # two directories up from $lcwd
PATH="$bindir:$PATH"
export bindir

if [ x"$VERBOSE" = x ]; then
	export VERBOSE=
fi

if [ x"$1" = x"-v" ]; then
	export VERBOSE=1
	shift
fi

implemented=$(
	printf "korego " # always implemented
	"$bindir/korego" --list-commands
	)

applets="$implemented"
if [ $# -ne 0 ]; then
	applets="$@"
fi

# Populate a directory with links to all busybox applets

LINKSDIR="$bindir/runtest-tempdir-links"
export LINKSDIR

# Comment this line out if you have put a different binary in $LINKSDIR
# (say, a "standard" tool's binary) in order to run tests against it:
rm -rf "$LINKSDIR" 2>/dev/null

mkdir "$LINKSDIR" 2>/dev/null
for i in $implemented; do
	# Note: if $LINKSDIR/applet exists, we do not overwrite it.
	# Useful if one wants to run tests against a standard utility,
	# not an applet.
	ln -s "$bindir/korego" "$LINKSDIR/$i" 2>/dev/null
done

# Create .config for tests that need it (e.g., md5sum checks CONFIG_FEATURE_FANCY_HEAD).
cat > "$bindir/.config" <<'CONFIGEOF'
CONFIG_FEATURE_FANCY_HEAD=y
CONFIG_FEATURE_MD5_SHA1_SUM_CHECK=y
CONFIG_FEATURE_TAR_CREATE=y
CONFIG_FEATURE_TAR_LONG_OPTIONS=y
CONFIG_FEATURE_TAR_GNU_EXTENSIONS=y
CONFIG_UNICODE_SUPPORT=y
CONFIG_DESKTOP=y
CONFIG_EXTRA_COMPAT=y
CONFIGEGREP=y
CONFIG_FEATURE_SEAMLESS_GZ=y
CONFIG_FEATURE_SEAMLESS_BZ2=y
CONFIG_FEATURE_SEAMLESS_XZ=y
CONFIG_FEATURE_TAR_AUTODETECT=y
CONFIG_FEATURE_SORT_BIG=y
CONFIG_FEATURE_TR_CLASSES=y
CONFIG_FEATURE_CUT_REGEX=y
CONFIG_FEATURE_DIFF_DIR=y
CONFIG_FEATURE_FIND_EXEC=y
CONFIG_FEATURE_FIND_EXEC_PLUS=y
CONFIG_FEATURE_FIND_MAXDEPTH=y
CONFIG_FEATURE_FIND_TYPE=y
CONFIG_FEATURE_READLINK_FOLLOW=y
CONFIG_FEATURE_XARGS_SUPPORT_QUOTES=y
CONFIG_FEATURE_XARGS_SUPPORT_REPL_STR=y
CONFIGEOF
# Build OPTIONFLAGS to enable tests for features KoreGo supports.
KOREGO_FEATURES="${KOREGO_FEATURES:-}"
OPTIONFLAGS=":"
# cat features
OPTIONFLAGS="${OPTIONFLAGS}FEATURE_CATV:FEATURE_CATN:"
# cut features
OPTIONFLAGS="${OPTIONFLAGS}FEATURE_CUT_REGEX:"
# diff features
OPTIONFLAGS="${OPTIONFLAGS}FEATURE_DIFF_DIR:"
# find features
OPTIONFLAGS="${OPTIONFLAGS}FEATURE_FIND_MAXDEPTH:FEATURE_FIND_TYPE:FEATURE_FIND_EXEC:FEATURE_FIND_EXEC_PLUS:"
# grep features
OPTIONFLAGS="${OPTIONFLAGS}EGREP:EXTRA_COMPAT:"
# head features
OPTIONFLAGS="${OPTIONFLAGS}FEATURE_FANCY_HEAD:"
# md5sum features
OPTIONFLAGS="${OPTIONFLAGS}FEATURE_MD5_SHA1_SUM_CHECK:"
# readlink features
OPTIONFLAGS="${OPTIONFLAGS}FEATURE_READLINK_FOLLOW:"
# sort features
OPTIONFLAGS="${OPTIONFLAGS}FEATURE_SORT_BIG:"
# tar features
OPTIONFLAGS="${OPTIONFLAGS}FEATURE_TAR_CREATE:FEATURE_TAR_LONG_OPTIONS:FEATURE_TAR_GNU_EXTENSIONS:"
# tr features
OPTIONFLAGS="${OPTIONFLAGS}FEATURE_TR_CLASSES:"
# xargs features
OPTIONFLAGS="${OPTIONFLAGS}FEATURE_XARGS_SUPPORT_QUOTES:FEATURE_XARGS_SUPPORT_REPL_STR:"
# Allow caller to append additional features
for f in $KOREGO_FEATURES; do
	OPTIONFLAGS="${OPTIONFLAGS}${f}:"
done
export OPTIONFLAGS

status=0
for applet in $applets; do
	# Any old-style tests for this applet?
	if [ -d "$tsdir/$applet" ]; then
		run_oldstyle_applet_tests "$applet" || status=1
	fi

	# Is this a new-style test?
	if [ -f "$applet.tests" ]; then
		if [ ! -e "$LINKSDIR/$applet" ]; then
			# (avoiding bash'ism "${applet:0:4}")
			if ! echo "$applet" | grep "^all_" >/dev/null; then
				echo "SKIPPED: $applet (not built)"
				continue
			fi
		fi
#		echo "Running test $tsdir/$applet.tests"
		PATH="$LINKSDIR:$tsdir:$bindir:$PATH" \
			"$tsdir/$applet.tests"
		rc=$?
		total_failed=$((total_failed + rc))
		test $rc -ne 0 && status=1
	fi
done

# Leaving the dir makes it somewhat easier to run failed test by hand
#rm -rf "$LINKSDIR"

if [ $status -ne 0 ] && [ x"$VERBOSE" = x ]; then
	echo "$total_failed failure(s) detected; running with -v (verbose) will give more info"
fi
exit $status
